---
- name: Download WordPress from the URL validate_certs=no to avoid errors
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  become: yes

- name: Extract WordPress from the directory I donwloaded it before
  unarchive:
    src=/tmp/wordpress.tar.gz
    dest=/var/www/
    copy=no
  become: yes

- name: Update default Apache site by replacing the line "(.)+DocumentRoot /var/www/html" by "DocumentRoot /var/www/wordpress"
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="DocumentRoot /var/www/html"
    line="        DocumentRoot /var/www/wordpress"
  notify:
  - Restart apache when default Apache site is updated
  become: yes

- name: Create the wp-config.php file and Move the content of wp-config-sample.php in the new php file
  command:
    mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
    creates=/var/www/wordpress/wp-config.php
  become: yes


- name: Deleting the "define( 'DB_NAME', '' );" line
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    line: define( 'DB_NAME', '' );
    state: absent

- name: Deleting the "define( 'DB_USER', '' );" line
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    line: define( 'DB_USER', '' );
    state: absent

- name: Deleting the "define( 'DB_PASSWORD', '' );" line
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    line: define( 'DB_PASSWORD', '' );
    state: absent

- name: Deleting the "require_once( ABSPATH . 'wp-settings.php' );" line
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    line: require_once( ABSPATH . 'wp-settings.php' );
    state: absent

- name: Update WordPress config file with the correct variables
  blockinfile:
    path: /var/www/wordpress/wp-config.php
    block: |
      define( 'DB_NAME', 'DB_wordpress' );
      define( 'DB_USER', 'user_wordpress' );
      define( 'DB_PASSWORD', 'password_wordpress' );
      define( 'UPLOADS', 'wp-content/uploads' );
      require_once( ABSPATH . 'wp-settings.php' );
  become: yes

- name: Giving access to the uploads directory
  command:
    chown -R www-data /var/www/wordpress/wp-content/uploads
  become: yes













